### ISSUE TITLE
[Bug] Track back error when running the script

### ISSUE THREAD

**Issue by andysingal** [okotaku/diffengine#34]
### Describe the bug

\[here\]

### To Reproduce

The command you executed.

```shell
# Training with diffengine config
!mim train diffengine stable_diffusion_v15_dreambooth_lora_dog.py \
  --cfg-options train_dataloader.dataset.class_image_config.num_images=50 \
  train_dataloader.batch_size=4 \
  train_cfg.max_iters=2000 \
  optim_wrapper.type='AmpOptimWrapper' \
  optim_wrapper.dtype='float16' \
  optim_wrapper.optimizer.lr=1e-5 \
  model.lora_config.rank=8
```

### Post related information

```
usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py:134: FutureWarning: Accessing config attribute `num_train_timesteps` directly via 'DDPMScheduler' object attribute is deprecated. Please access 'num_train_timesteps' over 'DDPMScheduler's config object instead, e.g. 'scheduler.config.num_train_timesteps'.
  deprecate("direct config name access", "1.0.0", deprecation_message, standard_warn=False)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/diffengine/.mim/tools/train.py", line 103, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/diffengine/.mim/tools/train.py", line 99, in main
    runner.train()
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py", line 1735, in train
    model = self.train_loop.run()  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/loops.py", line 278, in run
    self.run_iter(data_batch)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/loops.py", line 301, in run_iter
    outputs = self.runner.model.train_step(
  File "/usr/local/lib/python3.10/dist-packages/mmengine/model/base_model/base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/mmengine/model/base_model/base_model.py", line 340, in _run_forward
    results = self(**data, mode=mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffengine/models/editors/stable_diffusion/stable_diffusion.py", line 207, in forward
    model_pred = self.unet(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_condition.py", line 970, in forward
    sample = upsample_block(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_blocks.py", line 2134, in forward
    hidden_states = attn(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/transformer_2d.py", line 292, in forward
    hidden_states = block(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention.py", line 155, in forward
    attn_output = self.attn1(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 322, in forward
    return self.processor(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 1329, in __call__
    key = attn.to_k(encoder_hidden_states) + scale * self.to_k_lora(encoder_hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/lora.py", line 48, in forward
    return up_hidden_states.to(orig_dtype)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 14.75 GiB total capacity; 13.34 GiB already allocated; 2.81 MiB free; 13.46 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/usr/local/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mim/commands/train.py", line 100, in cli
    is_success, msg = train(
  File "/usr/local/lib/python3.10/dist-packages/mim/commands/train.py", line 261, in train
    ret = subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/usr/local/lib/python3.10/dist-packages/diffengine/.mim/tools/train.py', '/usr/local/lib/python3.10/dist-packages/diffengine/.mim/configs/stable_diffusion_dreambooth/stable_diffusion_v15_dreambooth_lora_dog.py', '--launcher', 'none', '--cfg-options', 'train_dataloader.dataset.class_image_config.num_images=50', 'train_dataloader.batch_size=4', 'train_cfg.max_iters=2000', 'optim_wrapper.type=AmpOptimWrapper', 'optim_wrapper.dtype=float16', 'optim_wrapper.optimizer.lr=1e-5', 'model.lora_config.rank=8']' returned non-zero exit status 1.
```

1. The output of `pip list | grep "mmengine\|diffusers\|transformers\|^torch"`
   \[here\]
2. Your config file if you modified it or created a new one.

```python
[here]
```

3. Your train log file if you meet the problem during training.
   \[here\]
4. Other code you modified in the `diffengine` folder.
   \[here\]

### Additional context

\[here\]

**Comment by okotaku** [comment]
@andysingal This is 'CUDA out of memory' error.

You can try following things.
1. Use with more powerful memory GPU like A6000.
2. Lower batch size.
'train_dataloader.batch_size=4' → 'train_dataloader.batch_size=1'

**Comment by okotaku** [comment]
@andysingal I created a Colaboratory example.
Please check it!
https://colab.research.google.com/drive/1vvwdj6yEj3GD5Z483JBlEU4sKCDXmidv
